# Doors
from org.bukkit.Material import (
    ACACIA_DOOR,
    BIRCH_DOOR,
    CRIMSON_DOOR,
    DARK_OAK_DOOR,
    IRON_DOOR,
    JUNGLE_DOOR,
    OAK_DOOR,
    SPRUCE_DOOR,
    WARPED_DOOR,
)

DOORS = (
    ACACIA_DOOR,
    BIRCH_DOOR,
    CRIMSON_DOOR,
    DARK_OAK_DOOR,
    IRON_DOOR,
    JUNGLE_DOOR,
    OAK_DOOR,
    SPRUCE_DOOR,
    WARPED_DOOR,
)

# TrapDoors
from org.bukkit.Material import (
    ACACIA_TRAPDOOR,
    BIRCH_TRAPDOOR,
    CRIMSON_TRAPDOOR,
    DARK_OAK_TRAPDOOR,
    IRON_TRAPDOOR,
    JUNGLE_TRAPDOOR,
    OAK_TRAPDOOR,
    SPRUCE_TRAPDOOR,
    WARPED_TRAPDOOR,
)

TRAPDOORS = (
    ACACIA_TRAPDOOR,
    BIRCH_TRAPDOOR,
    CRIMSON_TRAPDOOR,
    DARK_OAK_TRAPDOOR,
    IRON_TRAPDOOR,
    JUNGLE_TRAPDOOR,
    OAK_TRAPDOOR,
    SPRUCE_TRAPDOOR,
    WARPED_TRAPDOOR,
)


# Buttons

from org.bukkit.Material import (
    ACACIA_BUTTON,
    BIRCH_BUTTON,
    CRIMSON_BUTTON,
    DARK_OAK_BUTTON,
    JUNGLE_BUTTON,
    OAK_BUTTON,
    POLISHED_BLACKSTONE_BUTTON,
    SPRUCE_BUTTON,
    STONE_BUTTON,
    WARPED_BUTTON,
)

BUTTONS = (
    ACACIA_BUTTON,
    BIRCH_BUTTON,
    CRIMSON_BUTTON,
    DARK_OAK_BUTTON,
    JUNGLE_BUTTON,
    OAK_BUTTON,
    POLISHED_BLACKSTONE_BUTTON,
    SPRUCE_BUTTON,
    STONE_BUTTON,
    WARPED_BUTTON,
)


# PressurePlates
from org.bukkit.Material import (
    ACACIA_PRESSURE_PLATE,
    BIRCH_PRESSURE_PLATE,
    CRIMSON_PRESSURE_PLATE,
    DARK_OAK_PRESSURE_PLATE,
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    JUNGLE_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    SPRUCE_PRESSURE_PLATE,
    STONE_PRESSURE_PLATE,
    WARPED_PRESSURE_PLATE,
)

PRESSUREPLATES = (
    ACACIA_PRESSURE_PLATE,
    BIRCH_PRESSURE_PLATE,
    CRIMSON_PRESSURE_PLATE,
    DARK_OAK_PRESSURE_PLATE,
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    JUNGLE_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    SPRUCE_PRESSURE_PLATE,
    STONE_PRESSURE_PLATE,
    WARPED_PRESSURE_PLATE,
)
