# Doors
from org.bukkit.Material import (
    ACACIA_DOOR,
    BIRCH_DOOR,
    CRIMSON_DOOR,
    DARK_OAK_DOOR,
    IRON_DOOR,
    JUNGLE_DOOR,
    OAK_DOOR,
    SPRUCE_DOOR,
    WARPED_DOOR,
)

DOORS = (
    ACACIA_DOOR,
    BIRCH_DOOR,
    CRIMSON_DOOR,
    DARK_OAK_DOOR,
    IRON_DOOR,
    JUNGLE_DOOR,
    OAK_DOOR,
    SPRUCE_DOOR,
    WARPED_DOOR,
)

# TrapDoors
from org.bukkit.Material import (
    ACACIA_TRAPDOOR,
    BIRCH_TRAPDOOR,
    CRIMSON_TRAPDOOR,
    DARK_OAK_TRAPDOOR,
    IRON_TRAPDOOR,
    JUNGLE_TRAPDOOR,
    OAK_TRAPDOOR,
    SPRUCE_TRAPDOOR,
    WARPED_TRAPDOOR,
)

TRAPDOORS = (
    ACACIA_TRAPDOOR,
    BIRCH_TRAPDOOR,
    CRIMSON_TRAPDOOR,
    DARK_OAK_TRAPDOOR,
    IRON_TRAPDOOR,
    JUNGLE_TRAPDOOR,
    OAK_TRAPDOOR,
    SPRUCE_TRAPDOOR,
    WARPED_TRAPDOOR,
)


# Buttons

from org.bukkit.Material import (
    ACACIA_BUTTON,
    BIRCH_BUTTON,
    CRIMSON_BUTTON,
    DARK_OAK_BUTTON,
    JUNGLE_BUTTON,
    OAK_BUTTON,
    POLISHED_BLACKSTONE_BUTTON,
    SPRUCE_BUTTON,
    STONE_BUTTON,
    WARPED_BUTTON,
)

BUTTONS = (
    ACACIA_BUTTON,
    BIRCH_BUTTON,
    CRIMSON_BUTTON,
    DARK_OAK_BUTTON,
    JUNGLE_BUTTON,
    OAK_BUTTON,
    POLISHED_BLACKSTONE_BUTTON,
    SPRUCE_BUTTON,
    STONE_BUTTON,
    WARPED_BUTTON,
)


# PressurePlates
from org.bukkit.Material import (
    ACACIA_PRESSURE_PLATE,
    BIRCH_PRESSURE_PLATE,
    CRIMSON_PRESSURE_PLATE,
    DARK_OAK_PRESSURE_PLATE,
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    JUNGLE_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    SPRUCE_PRESSURE_PLATE,
    STONE_PRESSURE_PLATE,
    WARPED_PRESSURE_PLATE,
)

PRESSUREPLATES = (
    ACACIA_PRESSURE_PLATE,
    BIRCH_PRESSURE_PLATE,
    CRIMSON_PRESSURE_PLATE,
    DARK_OAK_PRESSURE_PLATE,
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    JUNGLE_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    OAK_PRESSURE_PLATE,
    SPRUCE_PRESSURE_PLATE,
    STONE_PRESSURE_PLATE,
    WARPED_PRESSURE_PLATE,
)

# Boats
from org.bukkit.Material import (
    ACACIA_BOAT,
    BIRCH_BOAT,
    DARK_OAK_BOAT,
    JUNGLE_BOAT,
    OAK_BOAT,
    SPRUCE_BOAT,
)

BOATS = (
    ACACIA_BOAT,
    BIRCH_BOAT,
    DARK_OAK_BOAT,
    JUNGLE_BOAT,
    OAK_BOAT,
    SPRUCE_BOAT,
)


# Heads
from org.bukkit.Material import (
    WITHER_SKELETON_SKULL,
    WITHER_SKELETON_WALL_SKULL,
    SKELETON_SKULL,
    SKELETON_WALL_SKULL,
    CREEPER_HEAD,
    CREEPER_WALL_HEAD,
    DRAGON_HEAD,
    DRAGON_WALL_HEAD,
    PLAYER_HEAD,
    PLAYER_WALL_HEAD,
    ZOMBIE_HEAD,
    ZOMBIE_WALL_HEAD,
)

HEADS = (
    WITHER_SKELETON_SKULL,
    WITHER_SKELETON_WALL_SKULL,
    SKELETON_SKULL,
    SKELETON_WALL_SKULL,
    CREEPER_HEAD,
    CREEPER_WALL_HEAD,
    DRAGON_HEAD,
    DRAGON_WALL_HEAD,
    PLAYER_HEAD,
    PLAYER_WALL_HEAD,
    ZOMBIE_HEAD,
    ZOMBIE_WALL_HEAD,
)

# Minecarts
from org.bukkit.Material import (
    CHEST_MINECART,
    COMMAND_BLOCK_MINECART,
    FURNACE_MINECART,
    HOPPER_MINECART,
    MINECART,
    TNT_MINECART,
)

MINECARTS = (
    CHEST_MINECART,
    COMMAND_BLOCK_MINECART,
    FURNACE_MINECART,
    HOPPER_MINECART,
    MINECART,
    TNT_MINECART,
)


BANNERS = (
    BLACK_BANNER,
    BLACK_WALL_BANNER,
    BLUE_BANNER,
    BLUE_WALL_BANNER,
    BROWN_BANNER,
    BROWN_WALL_BANNER,
    CREEPER_BANNER_PATTERN,
    CYAN_BANNER,
    CYAN_WALL_BANNER,
    FLOWER_BANNER_PATTERN,
    GLOBE_BANNER_PATTERN,
    GRAY_BANNER,
    GRAY_WALL_BANNER,
    GREEN_BANNER,
    GREEN_WALL_BANNER,
    LIGHT_BLUE_BANNER,
    LIGHT_BLUE_WALL_BANNER,
    LIGHT_GRAY_BANNER,
    LIGHT_GRAY_WALL_BANNER,
    LIME_BANNER,
    LIME_WALL_BANNER,
    MAGENTA_BANNER,
    MAGENTA_WALL_BANNER,
    MOJANG_BANNER_PATTERN,
    ORANGE_BANNER,
    ORANGE_WALL_BANNER,
    PIGLIN_BANNER_PATTERN,
    PINK_BANNER,
    PINK_WALL_BANNER,
    PURPLE_BANNER,
    PURPLE_WALL_BANNER,
    RED_BANNER,
    RED_WALL_BANNER,
    SKULL_BANNER_PATTERN,
    WHITE_BANNER,
    WHITE_WALL_BANNER,
    YELLOW_BANNER,
    YELLOW_WALL_BANNER,
)


# Placeable Entities
from org.bukkit.Material import (
    ARMOR_STAND,
    TORCH,
    WALL_TORCH,
    SOUL_TORCH,
    SOUL_WALL_TORCH,
    WITHER_SKELETON_SKULL,
    WITHER_SKELETON_WALL_SKULL,
)

ENTITY_ITEMS = (
    (
        ARMOR_STAND,
        TORCH,
        WALL_TORCH,
        SOUL_TORCH,
        SOUL_WALL_TORCH,
        WITHER_SKELETON_SKULL,
        WITHER_SKELETON_WALL_SKULL,
    )
    + BOATS
    + HEADS
    + MINECARTS
    + BANNERS
)
