from org.bukkit import Material
from org.bukkit.entity import EntityType

DamageClasses = ["PHYSICAL", "ELEMENTAL", "MAGIC"]

DefaultDamageTypes = {"PHYSICAL": "BLUDGEONING"}

DamageTypes = {
    "BLUDGEONING": "PHYSICAL",
    "HACKING": "PHYSICAL",
    "SLASHING": "PHYSICAL",
    "PIERCING": "PHYSICAL",
    "ACID": "ELEMENTAL",
    "FIRE": "ELEMENTAL",
    "COLD": "ELEMENTAL",
    "ENERGY": "ELEMENTAL",
    "NECROTIC": "MAGIC",
    "DIVINE": "MAGIC",
    "ARCANE": "MAGIC",
}


DefaultArmorTypes = {
    "ACID": 0,
    "HACKING": 0,
    "BLUDGEONING": 0,
    "NECROTIC": 0,
    "PIERCING": 0,
    "SLASHING": 0,
    "FIRE": 0,
    "COLD": 0,
    "DIVINE": 0,
    "ARCANE": 0,
    "ENERGY": 0,
}

ArmorTypes = {
    "LEATHER": {
        "ACID": -0.75,
        "HACKING": 0.25,
        "BLUDGEONING": 0.1,
        "NECROTIC": -0.25,
        "PIERCING": -0.25,
        "SLASHING": -0.25,
        "FIRE": -0.75,
        "COLD": -0.75,
        "DIVINE": 0.5,
        "ARCANE": 0.5,
        "ENERGY": -0.75,
    },
    "CHAIN": {
        "ACID": 0.15,
        "HACKING": 0.5,
        "BLUDGEONING": 0.5,
        "NECROTIC": 0.5,
        "PIERCING": -0.5,
        "SLASHING": -0.5,
        "FIRE": 0.15,
        "COLD": 0.15,
        "DIVINE": 0.5,
        "ARCANE": -0.5,
        "ENERGY": -1,
    },
    "IRON": {
        "ACID": -0.25,
        "HACKING": -0.5,
        "BLUDGEONING": -0.5,
        "NECROTIC": 0.5,
        "PIERCING": 0.25,
        "SLASHING": 0.25,
        "FIRE": 0.5,
        "COLD": 0.25,
        "DIVINE": 0.5,
        "ARCANE": -0.25,
        "ENERGY": 0.5,
    },
    "GOLD": {
        "ACID": 0.5,
        "HACKING": 0.15,
        "BLUDGEONING": 0.15,
        "NECROTIC": -0.75,
        "PIERCING": -0.15,
        "SLASHING": -0.15,
        "FIRE": -0.1,
        "COLD": -0.1,
        "DIVINE": -0.75,
        "ARCANE": -0.75,
        "ENERGY": 0.75,
    },
    "REDSTONE": {
        "ACID": 0.25,
        "HACKING": -0.1,
        "BLUDGEONING": -0.1,
        "NECROTIC": -0.5,
        "PIERCING": -0.1,
        "SLASHING": -0.1,
        "FIRE": 0.25,
        "COLD": -0.25,
        "DIVINE": -0.5,
        "ARCANE": -0.5,
        "ENERGY": -2,
    },
    "DIAMOND": {
        "ACID": -0.25,
        "HACKING": 0.15,
        "BLUDGEONING": 0.15,
        "NECROTIC": 0.5,
        "PIERCING": -0.25,
        "SLASHING": -0.25,
        "FIRE": -0.25,
        "COLD": 0.15,
        "DIVINE": 0.5,
        "ARCANE": 0.5,
        "ENERGY": 0.25,
    },
    "EMERALD": {
        "ACID": -0.1,
        "HACKING": 0.25,
        "BLUDGEONING": 0.25,
        "NECROTIC": -0.5,
        "PIERCING": -0.15,
        "SLASHING": -0.15,
        "FIRE": -0.1,
        "COLD": 0.25,
        "DIVINE": -0.5,
        "ARCANE": -0.5,
        "ENERGY": 0.25,
    },
}

ARMOR_TYPE_MAP = {
    Material.DIAMOND_HELMET: ArmorTypes["DIAMOND"],
    Material.DIAMOND_CHESTPLATE: ArmorTypes["DIAMOND"],
    Material.DIAMOND_LEGGINGS: ArmorTypes["DIAMOND"],
    Material.DIAMOND_BOOTS: ArmorTypes["DIAMOND"],
    Material.IRON_HELMET: ArmorTypes["IRON"],
    Material.IRON_CHESTPLATE: ArmorTypes["IRON"],
    Material.IRON_LEGGINGS: ArmorTypes["IRON"],
    Material.IRON_BOOTS: ArmorTypes["IRON"],
    Material.GOLDEN_HELMET: ArmorTypes["GOLD"],
    Material.GOLDEN_CHESTPLATE: ArmorTypes["GOLD"],
    Material.GOLDEN_LEGGINGS: ArmorTypes["GOLD"],
    Material.GOLDEN_BOOTS: ArmorTypes["GOLD"],
    Material.LEATHER_HELMET: ArmorTypes["LEATHER"],
    Material.LEATHER_CHESTPLATE: ArmorTypes["LEATHER"],
    Material.LEATHER_LEGGINGS: ArmorTypes["LEATHER"],
    Material.LEATHER_BOOTS: ArmorTypes["LEATHER"],
    Material.CHAINMAIL_HELMET: ArmorTypes["CHAIN"],
    Material.CHAINMAIL_CHESTPLATE: ArmorTypes["CHAIN"],
    Material.CHAINMAIL_LEGGINGS: ArmorTypes["CHAIN"],
    Material.CHAINMAIL_BOOTS: ArmorTypes["CHAIN"],
}

PHYSICAL_TYPE_MAP = {
    Material.WOODEN_AXE: "BLUDGEONING",
    Material.STONE_PICKAXE: "PIERCING",
    Material.DIAMOND_PICKAXE: "PIERCING",
    Material.IRON_PICKAXE: "PIERCING",
    Material.IRON_SWORD: "SLASHING",
    Material.GOLDEN_AXE: "HACKING",
    Material.DIAMOND_SHOVEL: "HACKING",
    Material.GOLDEN_SHOVEL: "HACKING",
    Material.STONE_AXE: "HACKING",
    Material.GOLDEN_PICKAXE: "PIERCING",
    Material.GOLDEN_SWORD: "SLASHING",
    Material.GOLDEN_AXE: "HACKING",
    Material.IRON_AXE: "HACKING",
    Material.WOODEN_SWORD: "HACKING",
    Material.IRON_SHOVEL: "HACKING",
    Material.DIAMOND_SWORD: "SLASHING",
    Material.WOODEN_PICKAXE: "PIERCING",
    Material.SHEARS: "SLASHING",
    Material.STONE_SWORD: "HACKING",
    Material.ARROW: "PIERCING",
}

ELEMENTAL_TYPE_MAP = {Material.TORCH: "FIRE"}

MAGIC_TYPE_MAP = {}

DAMAGE_TYPE_MAP = {
    "PHYSICAL": PHYSICAL_TYPE_MAP,
    "ELEMENTAL": ELEMENTAL_TYPE_MAP,
    "MAGIC": MAGIC_TYPE_MAP,
}

DEFAULT_ARMOR_SET = {
    "BLUDGEONING": 0,
    "HACKING": 0,
    "SLASHING": 0,
    "PIERCING": 0,
    "ACID": 0,
    "FIRE": 0,
    "COLD": 0,
    "ENERGY": 0,
    "NECROTIC": 0,
    "DIVINE": 0,
    "ARCANE": 0,
}


BATTLES_ARMOR_SETS = {
    EntityType.STRAY: {
        "BLUDGEONING": 0,
        "HACKING": 0,
        "SLASHING": 0,
        "PIERCING": 0,
        "ACID": 0,
        "FIRE": 1,
        "COLD": -0.25,
        "ENERGY": 0,
        "NECROTIC": 0,
        "DIVINE": 0,
        "ARCANE": 0,
    },
    EntityType.BLAZE: {
        "BLUDGEONING": 0,
        "HACKING": 0,
        "SLASHING": 0,
        "PIERCING": 0,
        "ACID": 0,
        "FIRE": -1,
        "COLD": 4,
        "ENERGY": 0,
        "NECROTIC": 0,
        "DIVINE": 0,
        "ARCANE": 0,
    },
    EntityType.GHAST: {
        "BLUDGEONING": 0,
        "HACKING": 0,
        "SLASHING": 0,
        "PIERCING": 0,
        "ACID": 0,
        "FIRE": -0.75,
        "COLD": 1.5,
        "ENERGY": 0,
        "NECROTIC": 0,
        "DIVINE": 0,
        "ARCANE": 0,
    },
    EntityType.MAGMA_CUBE: {
        "BLUDGEONING": 0,
        "HACKING": 0,
        "SLASHING": 0,
        "PIERCING": 0,
        "ACID": 0,
        "FIRE": -0.9,
        "COLD": 3,
        "ENERGY": 0,
        "NECROTIC": 0,
        "DIVINE": 0,
        "ARCANE": 0,
    },
    EntityType.ZOMBIFIED_PIGLIN: {
        "BLUDGEONING": 0,
        "HACKING": 0,
        "SLASHING": 0,
        "PIERCING": 0,
        "ACID": 0,
        "FIRE": -0.75,
        "COLD": 0.5,
        "ENERGY": 0,
        "NECROTIC": 0,
        "DIVINE": 0,
        "ARCANE": 0,
    },
    EntityType.WITHER_SKELETON: {
        "BLUDGEONING": 0,
        "HACKING": 0,
        "SLASHING": 0,
        "PIERCING": 0,
        "ACID": 0,
        "FIRE": -0.75,
        "COLD": 1,
        "ENERGY": 0,
        "NECROTIC": 0,
        "DIVINE": 0,
        "ARCANE": 0,
    },
}
